add phpunit tests
ykuzakova/php-course pull request #10
Opened 2022-04-17 16:36 UTC by ykuzakova

2022-05-16 07:37 UTC, ova777 requested changes
Всё правильно сделано, но есть недочеты

2022-05-16 07:37 UTC, ova777 commented on tests/Tasks/Ex1Test.php
> +        $this->getExpectedException(\InvalidArgumentException::class);
`getExpectedException` возвращает exception, который до этого установили с помощью `expectException`. Соответственно тут нужен `expectException`.

2022-05-16 07:37 UTC, ova777 commented on tests/Tasks/Ex2Test.php
> +    public function testIsPowerOfThree(int $num, int $expected): void
`$expected` должен быть bool, т.к. `isPowerOfThree` возвращает bool.

2022-05-16 07:37 UTC, ova777 commented on tests/Tasks/Ex3Test.php
> +class Ex3Test extends TestCase
Не хватает теста на Exception

2022-05-16 07:37 UTC, ova777 commented on tests/Tasks/Ex4Test.php
> +class Ex4Test extends TestCase
Не хватает теста на Exception

2022-05-16 07:37 UTC, ova777 commented on tests/Tasks/Ex6Test.php
> +        [-1, \Exception::class],
Не хватает отступа слева

2022-05-25 09:35 UTC, ykuzakova commented on tests/Tasks/Ex1Test.php
> +        $this->getExpectedException(\InvalidArgumentException::class);
fixed

2022-05-25 09:35 UTC, ykuzakova commented on tests/Tasks/Ex2Test.php
> +    public function testIsPowerOfThree(int $num, int $expected): void
fixed

2022-05-25 09:36 UTC, ykuzakova commented on tests/Tasks/Ex3Test.php
> +class Ex3Test extends TestCase
fixed

2022-05-25 09:36 UTC, ykuzakova commented on tests/Tasks/Ex4Test.php
> +class Ex4Test extends TestCase
fixed

2022-05-25 09:37 UTC, ykuzakova commented on tests/Tasks/Ex6Test.php
> +        [-1, \Exception::class],
lint не ругается. Подскажи, пожалуйста, в какой строке отступа не хватает?

2022-05-25 10:05 UTC, ova777 approved these changes

2022-05-25 13:55 UTC, merged