ex6 done
ykuzakova/php-course pull request #6
Opened 2022-03-15 14:24 UTC by ykuzakova

2022-03-15 14:34 UTC, ovaunit requested changes

2022-03-15 14:34 UTC, ovaunit commented on ex6/index.php
> +    if ($num === $sum) {
Этот if можно оптимизировать.
`$num === $sum` принимает значение true/false, и возвращаешь ты true/false.
Соответственно можно просто вернуть `$num === $sum`

2022-03-15 14:34 UTC, ovaunit commented on ex6/index.php
> +function isPerfect(int $num): bool
Твоя функция говорит что 0 - совершенное число, хотя совершенными являются только положительные

2022-03-21 03:15 UTC, ykuzakova commented on ex6/index.php
> +    if ($num === $sum) {
fixed

2022-03-21 03:15 UTC, ykuzakova commented on ex6/index.php
> +function isPerfect(int $num): bool
fixed

2022-03-21 08:01 UTC, ova777 approved these changes

2022-03-21 08:03 UTC, merged