Add classes and exceptions
ykuzakova/php-course pull request #9
Opened 2022-04-05 09:56 UTC by ykuzakova

2022-04-07 05:18 UTC, ova777 requested changes

2022-04-07 05:18 UTC, ova777 commented on src/Tasks/Ex1.php
> +        if('' === $bin1 || '' === $bin2) {
Пробел после if

2022-04-07 05:18 UTC, ova777 commented on src/Tasks/Ex3.php
> +    public function fib(int $num):int
Пробел после `:`

2022-04-07 05:18 UTC, ova777 commented on src/Tasks/Ex4.php
> +        {
Зачем весь код обернут в дополнительные фигурные скобки?

2022-04-07 05:18 UTC, ova777 commented on src/Tasks/Ex5.php
> +   public function isBalanced(string $str): bool
Отступ должен быть 4 пробела (тут 3)

2022-04-07 05:18 UTC, ova777 commented on src/Tasks/Ex5.php
> +        if ($str = 'test') {
Тут ты делаешь присвоение, соответственно это условие всегда будет истинно

2022-04-07 05:18 UTC, ova777 commented on src/Tasks/Ex8.php
> +    function fizzBuzz(int $begin, int $end)
Нужно указать return type (тут будет void)

2022-04-08 02:43 UTC, ykuzakova commented on src/Tasks/Ex1.php
> +        if('' === $bin1 || '' === $bin2) {
fixed

2022-04-08 02:44 UTC, ykuzakova commented on src/Tasks/Ex3.php
> +    public function fib(int $num):int
fixed

2022-04-08 02:44 UTC, ykuzakova commented on src/Tasks/Ex4.php
> +        {
fixed

2022-04-08 02:44 UTC, ykuzakova commented on src/Tasks/Ex5.php
> +   public function isBalanced(string $str): bool
fixed

2022-04-08 02:44 UTC, ykuzakova commented on src/Tasks/Ex5.php
> +        if ($str = 'test') {
fixed (deleted)

2022-04-08 02:44 UTC, ykuzakova commented on src/Tasks/Ex8.php
> +    function fizzBuzz(int $begin, int $end)
fixed

2022-04-08 03:17 UTC, merged